name: Release VS Code Extension

on:
  release:
    types: [created]

permissions: write-all

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'
      
      - name: Install VSCE
        run: npm install -g vsce

      - name: Install Dependencies
        run: cd vscode_ext && npm install

      - name: Package Extension
        run: cd vscode_ext && vsce package

      - name: Upload VSIX as Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./vscode_ext/*.vsix
          asset_name: gopatch-syntax.vsix
          asset_content_type: application/octet-stream
